# Generated by Django 4.0.2 on 2022-03-16 22:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(error_messages={'blank': 'Název klubu musí být vyplněn'}, help_text='Zadejte název klubu', max_length=50, verbose_name='Název klubu')),
                ('misto', models.CharField(error_messages={'blank': 'Jméno města nebo obce musí být vyplněno'}, help_text='Zadejte jméno města nebo obce', max_length=30, verbose_name='Město (obec)')),
                ('zalozeni', models.IntegerField(blank=True, help_text='Zadejte rok založení', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2022)], verbose_name='Rok založení')),
            ],
            options={
                'verbose_name': 'Klub',
                'verbose_name_plural': 'Kluby',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Cyklista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(error_messages={'blank': 'Jméno cyklisty musí být vyplněno'}, help_text='Zadejte jméno cyklisty', max_length=50, verbose_name='Jméno')),
                ('prijmeni', models.CharField(error_messages={'blank': 'Příjmení cyklisty musí být vyplněno'}, help_text='Zadejte příjmení cyklisty', max_length=50, verbose_name='Příjmení')),
                ('narozeni', models.DateField(blank=True, help_text='Zadejte datum narození', verbose_name='Datum narození')),
                ('fotka', models.ImageField(blank=True, upload_to='fotky', verbose_name='Fotka cyklisty')),
                ('kariera', models.TextField(blank=True, verbose_name='Kariéra')),
                ('klub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zavody.klub', verbose_name='Klub')),
            ],
            options={
                'verbose_name': 'Cyklista',
                'verbose_name_plural': 'Cyklisté',
                'ordering': ['prijmeni', 'jmeno'],
            },
        ),
    ]
