# Generated by Django 4.2 on 2023-04-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zavody', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='klub',
            name='logo',
            field=models.ImageField(blank=True, help_text='Zadejte logo klubu', upload_to='loga', verbose_name='Logo klubu'),
        ),
    ]
