# Generated by Django 4.0.4 on 2023-03-24 19:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zavody', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='klub',
            name='logo',
            field=models.ImageField(blank=True, help_text='Zadejte logo klubu', upload_to='loga', verbose_name='Logo klubu'),
        ),
        migrations.AlterField(
            model_name='klub',
            name='zalozeni',
            field=models.IntegerField(blank=True, help_text='Zadejte rok založení', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)], verbose_name='Rok založení'),
        ),
        migrations.CreateModel(
            name='Zavod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(error_messages={'blank': 'Název závodu musí být vyplněn'}, help_text='Zadejte název zavodu', max_length=100, verbose_name='Název zavodu')),
                ('datum_konani', models.DateField(error_messages={'blank': 'Datum konání závodu musí být vyplněno'}, help_text='Zadej datum konání závodu', verbose_name='Datum konání')),
                ('informace', models.TextField(blank=True, verbose_name='Podrobnější informace')),
                ('delka', models.PositiveIntegerField(blank=True, help_text='Zadejte délku trasy závodu v rozsahu 1 - 300 km', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)], verbose_name='Délka trasy')),
                ('klub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zavody.klub', verbose_name='Klub pořádající závod')),
                ('ucastnici', models.ManyToManyField(blank=True, to='zavody.cyklista', verbose_name='Účastníci závodu')),
            ],
        ),
    ]
